name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: first stage
      run: echo Hello, world!
    - name: second stage
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
